version: '3'

tasks:
  default:
    deps: [build]

  build:
    desc: Build all commands in cmd/ into bin/
    sources:
      - cmd/**/*.go
      - internal/**/*.go
    generates:
      - bin/wfinfo-go
    cmds:
      - mkdir -p bin
      - go build -o bin/wfinfo-go ./cmd/wfinfo-go

  test:
    desc: Run tests
    cmds:
      - go test -v ./internal/... -count=1

  run:
    desc: Run the wfinfo-go binary
    deps: [build]
    cmds:
      - ./bin/wfinfo-go

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf bin

  install:
    desc: Install the binary (defaults to /usr/local/bin)
    deps: [build]
    vars:
      PREFIX: '{{default "/usr/local" .PREFIX}}'
    cmds:
      - sudo install -D bin/wfinfo-go {{.PREFIX}}/bin/wfinfo-go

  uninstall:
    desc: Uninstall the binary (defaults to /usr/local/bin)
    vars:
      PREFIX: '{{default "/usr/local" .PREFIX}}'
    cmds:
      - sudo rm -f {{.PREFIX}}/bin/wfinfo-go
